/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ventana;

import javax.swing.JOptionPane;
import metromendeley.Functions;
import metromendeley.GlobalVariables;
import metromendeley.List;
import metromendeley.ListObject;
import metromendeley.Node;
import metromendeley.NodeObject;
import metromendeley.infoObject;

/**
 *
 * @author leste
 */
public final class Autor extends javax.swing.JFrame {

    /**
     * Creates new form Autor
     */
    public Autor() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        AllAuthors();
    }
    
        public void AllAuthors() {
        ListObject lista = GlobalVariables.getObjetos();
        NodeObject pointer = lista.getHead();
        int index = 0;
        while (pointer != null) {
            infoObject summary = pointer.getElement();
            String[] autores = summary.getAutores();
            for (int i = 0; i < autores.length; i++) {        
                Autores.insertItemAt(autores[i], index);
                index++;
            }
            pointer = pointer.getNext();
        }
        //for (int j = 0; i < Autores.getItemListeners().length; i++){ 
        //String value = String.valueOf(Autores.getItemListeners()[i]);
        // }
    }
        
        public void AllSummaries(){
            ListObject lista = GlobalVariables.getObjetos();
            NodeObject pointer = lista.getHead();
            int index = 0;
            while (pointer != null) {
                infoObject summary = pointer.getElement();
                String[] autores = summary.getAutores();
                for (int i = 0; i < autores.length; i++) {        
                    if (autores[i].equals(String.valueOf(Autores.getSelectedItem()))) {
                        Investigaciones.insertItemAt(summary.getTitle(), index);
                        index++;
                    }      
                }
                pointer = pointer.getNext();
            }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Salir = new javax.swing.JButton();
        Investigaciones = new javax.swing.JComboBox<>();
        Autores = new javax.swing.JComboBox<>();
        titulos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resumen = new javax.swing.JTextArea();
        jlabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        crearInvestigaciones = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Busqueda por Autor ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        Salir.setBackground(new java.awt.Color(153, 255, 153));
        Salir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Salir.setText("Menu");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 100, 40));

        Investigaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InvestigacionesActionPerformed(evt);
            }
        });
        jPanel1.add(Investigaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 290, 30));

        jPanel1.add(Autores, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 140, -1));

        titulos.setBackground(new java.awt.Color(204, 204, 255));
        titulos.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        titulos.setText("Información de Investigación");
        titulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titulosActionPerformed(evt);
            }
        });
        jPanel1.add(titulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 220, 40));

        resumen.setColumns(20);
        resumen.setRows(5);
        jScrollPane1.setViewportView(resumen);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 470, 150));

        jlabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jlabel5.setText("Investigaciones");
        jPanel1.add(jlabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Autores");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 50, -1));

        crearInvestigaciones.setBackground(new java.awt.Color(204, 255, 204));
        crearInvestigaciones.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        crearInvestigaciones.setText("Buscar Investigaciones de Autor");
        crearInvestigaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearInvestigacionesActionPerformed(evt);
            }
        });
        jPanel1.add(crearInvestigaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/busqueda.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        Menu m = new Menu();
        this.setVisible(false);
        m.setVisible(true);
    }//GEN-LAST:event_SalirActionPerformed

    private void InvestigacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InvestigacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InvestigacionesActionPerformed

    private void titulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titulosActionPerformed
        Functions v = new Functions();
        if (Investigaciones.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "No agrego ningun elemento.");
        }
        else{
            String p = GlobalVariables.getTable().buscarObjeto(String.valueOf(Investigaciones.getSelectedItem())).createInfo();
            resumen.setText(p);
        }
    }//GEN-LAST:event_titulosActionPerformed

    private void crearInvestigacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearInvestigacionesActionPerformed
        int itemCount = Investigaciones.getItemCount();
            for(int i = 0; i < itemCount; i++){
            Investigaciones.removeItemAt(0);
            }
        AllSummaries();
    }//GEN-LAST:event_crearInvestigacionesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Autor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Autor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Autor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Autor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Autor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Autores;
    private javax.swing.JComboBox<String> Investigaciones;
    private javax.swing.JButton Salir;
    private javax.swing.JButton crearInvestigaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel5;
    private javax.swing.JTextArea resumen;
    private javax.swing.JButton titulos;
    // End of variables declaration//GEN-END:variables
}
